#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
import RPi.GPIO as GPIO
from std_msgs.msg import String, UInt8
import time                                          

cnt= 0
btn_io= 16

GPIO.setmode(GPIO.BCM)
GPIO.setup(btn_io, GPIO.IN, pull_up_down= GPIO.PUD_UP)

GPIO.setup(20,GPIO.OUT)#
GPIO.output(20,0)



def callback(data):
    pub_feedback= rospy.Publisher('feedback', String, queue_size= 10)
    global cnt
    cnt= cnt + 1
    if cnt == 5:
        rospy.loginfo(rospy.get_caller_id() + ' I heard %s \n', data.data)
        cnt= 0 
        feedback= 'count to 5, \n'
        pub_feedback.publish(feedback)


def led_callback(data):#
    if data.data == 1:#
        rospy.loginfo('led_in')
        GPIO.output(20,1)#
        time.sleep(1)
    else:#
        rospy.loginfo('led_off')
        GPIO.output(20,0)#

def listener():
    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber('chatter', UInt8, led_callback)

    
    rospy.spin()

if __name__== '__main__':
    listener()
    GPIO.cleanup()
