#!/usr/bin/env python
import rospy
from std_msgs.msg import String
from std_srvs.srv import SetBool
import RPi.GPIO as GPIO

LED_GPIO = 20

def callback(data):
    rospy.loginfo(rospy.get_caller_id()+"I heard %s",data.data)
    
def set_led_state_callback(req):
    GPIO.output(LED_GPIO, req.data)
    return {'success':True,'message':'Successfully changed LED state'}

def listener():
    rospy.init_node("listener",anonymous=True)
    rospy.Subscriber("chatter",String,callback)
    rospy.spin()

if __name__=="__main__":
    rospy.init_node("led_actuator")
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(LED_GPIO,GPIO.OUT)
    rospy.Service("set_led_state",SetBool,set_led_state_callback)
    rospy.loginfo("Service server started. Ready to get requests.")
    rospy.spin()
    GPIO.cleanup()
    listener()